### Get Booking by bookingID id={{bookingId}}
GET http://localhost:8082/v1/booking/get?id=













### temp Reserve given Seats
POST http://localhost:8082/v1/booking/tempReserve
Content-Type: application/json

[
  {
    "eventID": "3eddcec1-29dc-4667-afb3-3333ea248e48",
    "row": 2,
    "place": 1,
    "userId": "62ee6730-16a4-4546-90c1-b12a76356464"
  }
]

### fully reserve given Seats
POST http://localhost:8082/v1/booking/reserve
Content-Type: application/json

[
  {
    "userID": "baf5893f-538d-48a7-ad7c-7a824ec0d0d4",
    "eventID": "7b07184c-be6d-423b-9972-a343adac87a2",
    "row": 1,
    "place": 1
  },
  {
    "userID": "baf5893f-538d-48a7-ad7c-7a824ec0d0d4",
    "eventID": "7b07184c-be6d-423b-9972-a343adac87a2",
    "row": 1,
    "place": 2
  }
]

### scan qr code
POST http://localhost:8082/v1/booking/scan?code={{code}}