### Get Booking by bookingID id={{bookingId}}
GET http://localhost:8082/v1/booking/get?id=



### temp Reserve given Seats
POST http://localhost:8082/v1/booking/tempReserve
Content-Type: application/json

[
  {
    "eventID": "3eddcec1-29dc-4667-afb3-3333ea248e48",
    "row": 2,
    "place": 1,
    "userId": "62ee6730-16a4-4546-90c1-b12a76356464"
  }
]

### fully reserve given Seats
POST http://localhost:8082/v1/booking/reserve
Content-Type: application/json

[
  {
    "userID": "775b778a-8feb-48df-9527-28e54675937e",
    "eventID": "b93fbf96-7a02-457b-8811-11145c2d8c3a",
    "row": 1,
    "place": 1
  },
  {
    "userID": "b93fbf96-7a02-457b-8811-11145c2d8c3a",
    "eventID": "4e6f9d30-64ee-431b-b4b5-c5dd1d88ee99",
    "row": 1,
    "place": 2
  }
]

### scan qr code
POST http://localhost:8082/v1/booking/scan?code={{code}}