### Get all
GET http://localhost:8082/v1/cinemaHall/getAll

### Get by id
GET http://localhost:8082/v1/cinemaHall/get/{{cinemaHallId}}

### Add cinema hall
POST http://localhost:8082/v1/cinemaHall/add
Content-Type: application/json

{
  "cinemaId": "insert id here",
  "rows": 12,
  "placesPerRow": 20,
  "name": "Gottes Halle",
  "floor": 2
}