### Get all
GET http://localhost:8082/v1/cinemaHall/get?cinemaId={{cinemaId}}

### Get by id
GET http://localhost:8082/v1/cinemaHall/get?id={{cinemaHallId}}

### Add cinema hall
POST http://localhost:8082/v1/cinemaHall/add
Content-Type: application/json

{
  "cinemaId": "f16fdf6e-1fdc-41f6-b866-462ec270764e",
  "rows": 12,
  "placesPerRow": 20,
  "name": "Gottes Halle",
  "floor": 2
}