### Get all cities
GET http://localhost:8082/v1/city/getAll

### Get city by plz
GET http://localhost:8082/v1/city/getByPlz/{{plz}}

### Get city by name
GET http://localhost:8082/v1/city/getByCityName/{{cityName}}