### Get all events by movie
GET http://localhost:8082/v1/event/get?movieId={{movieId}}

### Get event by id
GET http://localhost:8082/v1/event/get?id={{eventId}}

### Get events between two dates
# DATE_TIME_FORMATTER = "dd-MM-yyyy HH:mm" -> "02-12-2023 18:00"
GET http://localhost:8082/v1/event/get?startDate={{startDate}}&endDate={{endDate}}

### Get events between two dates by movie
GET http://localhost:8082/v1/event/get?movieId={{movieId}}&startDate={{startDate}}&endDate={{endDate}}

### Get events for a specific day
# DATE_FORMATTER = "dd-MM-yyyy" -> "02-12-2023"
GET http://localhost:8082/v1/event/get?date={{date}}

### Get events for a specific day by movie
GET http://localhost:8082/v1/event/get?movieId={{movieId}}&date={{date}}

### Add new event
POST http://localhost:8082/v1/event/add
Content-Type: application/json

{
  "movieId": "1329d282-fca2-44ee-9c4f-9693e117333f",
  "cinemaHallId": "38b17532-9813-4e35-a945-4b500de0a16d",
  "eventDateTime": "12-02-2023 18:00"
}