### Upload a large JPG file - compressed
POST http://localhost:8082/v1/image/add
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="file.jpeg"
Content-Type: image/jpeg

// The 'input.txt' file will be uploaded
< ./ressources/astronaut.jpg
--WebAppBoundary


### Upload a JPG file - uncompressed
POST http://localhost:8082/v1/image/add
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="file.jpeg"
Content-Type: image/jpeg

// The 'input.txt' file will be uploaded
< ./ressources/avatar.jpg
--WebAppBoundary

### Upload a JPG file - to big to compress
POST http://localhost:8082/v1/image/add
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="file.jpeg"
Content-Type: image/jpeg

// The 'input.txt' file will be uploaded
< ./ressources/rocky.jpg
--WebAppBoundary


### Download the requested image. Set the UUID yourself
GET http://localhost:8082/v1/image/get/09188d06-4a7e-44bb-b873-570e0089add7

