### Get all Movies
GET http://localhost:8082/v1/movie/getAll
Content-Type: application/json

### Add a new Movie
### Get example Data for Actors from http://localhost:8082/v1/actor/getAll (ActorController.http)
POST http://localhost:8082/v1/movie/add
Content-Type: application/json

{
  "producerName": "MarvelStudios",
  "directorFirstName": "Quentin",
  "directorLastName": "Tarrentino",
  "actors": {
    "5acce576-f74e-4e0b-9689-8bebd8290a67": "Manfred Schneider"
  },
  "image": "c35d2d69-6f6b-4630-a7c7-2d83242570a2",
  "fsk": 12,
  "genre": "Action",
  "name": "Der große Testfilm",
  "description": "Dieser Film ist ein Test",
  "rating": 6.4,
  "length": 82,
  "start_date": "08-01-2023",
  "end_date": "08-04-2023"
}

### Add a new Movie with false Genre
POST http://localhost:8082/v1/movie/add
Content-Type: application/json

{
  "producerName": "MarvelStudios",
  "directorFirstName": "Quentin",
  "directorLastName": "Tarrentino",
  "actors": [
    "13fc962e-d622-443a-83da-b3f42194211a"
  ],
  "image": "5336cb4b-1279-4a31-97fb-df1a7acdd047",
  "fsk": 12,
  "genre": "ActionPP",
  "name": "Der große Testfilm",
  "description": "Dieser Film ist ein Test",
  "rating": 6.4,
  "length": 82,
  "start_date": "08-01-2023",
  "end_date": "08-04-2023"
}

### Add a new Movie with false FSK
POST http://localhost:8082/v1/movie/add
Content-Type: application/json

{
  "producerName": "MarvelStudios",
  "directorFirstName": "Quentin",
  "directorLastName": "Tarrentino",
  "actors": [
    "13fc962e-d622-443a-83da-b3f42194211a"
  ],
  "image": "5336cb4b-1279-4a31-97fb-df1a7acdd047",
  "fsk": 10,
  "genre": "ActionPP",
  "name": "Der große Testfilm",
  "description": "Dieser Film ist ein Test",
  "rating": 6.4,
  "length": 82,
  "start_date": "08-01-2023",
  "end_date": "08-04-2023"
}