### Get all Movies
GET http://localhost:8082/v1/movie/getAll
Content-Type: application/json

### Add a new Movie
### Get example Data for Actors from http://localhost:8082/v1/actor/getAll (ActorController.http)
POST http://localhost:8082/v1/movie/add
Content-Type: application/json

{
  "producerName": "MarvelStudios",
  "directorFirstName": "Quentin",
  "directorLastName": "Tarrentino",
  "actors": {
    "f7d07703-d603-4338-8f82-800a55de685c": "Manfred Schneider"
  },
  "image": "74940876-d980-4d92-b5b8-cdefa531730d",
  "fsk": 12,
  "genre": "Action",
  "name": "Der große Testfilm",
  "description": "Dieser Film ist ein Test",
  "rating": 6.4,
  "length": 82,
  "start_date": "08-01-2023",
  "end_date": "08-04-2023"
}

### Add a new Movie with false Genre
POST http://localhost:8082/v1/movie/add
Content-Type: application/json

{
  "producerName": "MarvelStudios",
  "directorFirstName": "Quentin",
  "directorLastName": "Tarrentino",
  "actors": [
    "13fc962e-d622-443a-83da-b3f42194211a"
  ],
  "image": "5336cb4b-1279-4a31-97fb-df1a7acdd047",
  "fsk": 12,
  "genre": "ActionPP",
  "name": "Der große Testfilm",
  "description": "Dieser Film ist ein Test",
  "rating": 6.4,
  "length": 82,
  "start_date": "08-01-2023",
  "end_date": "08-04-2023"
}

### Add a new Movie with false FSK
POST http://localhost:8082/v1/movie/add
Content-Type: application/json

{
  "producerName": "MarvelStudios",
  "directorFirstName": "Quentin",
  "directorLastName": "Tarrentino",
  "actors": [
    "13fc962e-d622-443a-83da-b3f42194211a"
  ],
  "image": "5336cb4b-1279-4a31-97fb-df1a7acdd047",
  "fsk": 10,
  "genre": "ActionPP",
  "name": "Der große Testfilm",
  "description": "Dieser Film ist ein Test",
  "rating": 6.4,
  "length": 82,
  "start_date": "08-01-2023",
  "end_date": "08-04-2023"
}