### Add new tmdb movie into our db
POST http://localhost:8082/v1/movie/tmdb/addTmdb
Content-Type: application/json

{
  "tmdbMovieId": 11
}

### Get tmdb movies by query-name
GET http://localhost:8082/v1/movie/tmdb/getTmdb?movieName="Star Wars"

### Get tmdb movie by id
GET http://localhost:8082/v1/movie/tmdb/getTmdb?movieId={{tmdbMovieId}}