name: Java CI with Maven

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'microsoft'
        cache: maven
        
    - name: Build with Maven and create Coverage
      run: mvn -B package --file pom.xml
      
    - name: Upload Report 
      uses: 'actions/upload-artifact@v2'
      with:
        name: report.xml
        path: ${{ github.workspace }}/build/reports/jacoco/testCoverage/testCoverage.xml

    - name: Jacoco Report to PR
      id: jacoco
      uses: Madrapps/jacoco-report@v1.3
      with:
        path: ${{ github.workspace }}/build/reports/jacoco/testCoverage/testCoverage.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 85
        min-coverage-changed-files: 90
        title: 'Coverages on latest commit:'
        debug-mode: false

    - name: Get the Coverage info
      run: |
        echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
        echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
      
